kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-data-uat
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/opt/rabbitmq-data-uat"
